downscale now uses dtrt-ffmpeg.zsh
also added support of configurable upscale

diff --git a/bin/dtrt-ffmpeg-downscale b/bin/dtrt-ffmpeg-downscale
--- a/bin/dtrt-ffmpeg-downscale
+++ b/bin/dtrt-ffmpeg-downscale
@@ -1,16 +1,13 @@
+#! /usr/bin/env zsh
 # TODO: the current output_template is insecure
 # (as a backtrick in it or in the file name can have remote code execution )
 # TODO: scale is a mock
 # don't really use arguements to decide everything
+# TODO: fallback when GPU fail (cuvid and nvenc)
 
-use_slurm=false use_cuvid=false
-. ~/.ffdtrt
+. ddrt-ffmpeg.zsh
 
-alias @='for it'
-alias @-='while {read it}'
-setopt nounset warncreateglobal
 encoder=()
-
 available_sizes=(
     320.240
     720.480
@@ -18,13 +15,12 @@ available_sizes=(
     1920.1080
 )
 
+scaling_args () { encoder+=( -vf scale=$width\x$height ) }
+encoder=( ffmpeg )
 
-if {$use_cuvid} {
+$use_cuvid && {
     scaling_args () { encoder+=( -vf scale_nnp=$width\x$height ) }
     encoder=( ffmpeg -hwaccel cuvid -c:v h264_cuvid )
-} else {
-    scaling_args () { encoder+=( -vf scale=$width\x$height ) }
-    encoder=( ffmpeg )
 }
 
 reads () { @ { typeset -g $it; read $it; } }
@@ -50,10 +46,11 @@ output () {
     output_template=${1?template for the path of output file}
 }
 
-required_output () {
+upscale_almost () {
+    local tolerance=${1?a tolerence in decimal notation (aka .1 for 10%)}
     (( ( input_height != height )
        && (( input_height > height )
-        || ( ( height - input_height ) < ( input_height * .1 ) ))))
+        || ( ( height - input_height ) < ( input_height * tolerance ) ))))
 }
 
 scale () {
@@ -77,7 +74,7 @@ template=${1?the template for output file}
 for doit {
     input $doit
     # ffprobe_dump_in out/info $input
-    output 'out/${input:t:r}_${width}x${height}.${input:e}'
+    output '${workdir}/${input:t:r}_${width}x${height}.${input:e}'
     scale always 240 downscale  upscale_almost '10%'
     encode
 }
